{{- $cert := genSelfSignedCert "rapitester" nil nil 365 -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret-tls
type: kubernetes.io/tls
data:
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
